typedef struct {
  uint16_t paragraph;
  uint16_t inline_node;
  uint16_t block_continuation;
  uint16_t atx_heading;
  uint16_t setext_heading;
  uint16_t setext_h1;
  uint16_t pipe_table;
  uint16_t pipe_table_delimiter_row;
  uint16_t thematic_break;
  uint16_t block_quote;
  uint16_t block_quote_marker;
  uint16_t list;
  uint16_t list_item;
  uint16_t marker_dot;
  uint16_t marker_paren;
  uint16_t task_checked;
  uint16_t task_unchecked;
  uint16_t fenced_code_block;
  uint16_t code_fence_content;
  uint16_t fence_delimiter;
  uint16_t info_string;
  uint16_t indented_code_block;
  uint16_t html_block;
  uint16_t minus_metadata;
  uint16_t plus_metadata;
  uint16_t atx_markers[6];
  uint16_t list_markers[5];
} Ids;
static inline uint16_t symbol(const TSLanguage *lang, const char *s) {
  return ts_language_symbol_for_name(lang, s, strlen(s), true);
}
static inline Ids make_ids(const TSLanguage *lang) {
  Ids ids = {0};
  ids.paragraph = symbol(lang, "paragraph");
  ids.inline_node = symbol(lang, "inline");
  ids.block_continuation = symbol(lang, "block_continuation");
  ids.atx_heading = symbol(lang, "atx_heading");
  ids.setext_heading = symbol(lang, "setext_heading");
  ids.setext_h1 = symbol(lang, "setext_h1_underline");
  ids.pipe_table = symbol(lang, "pipe_table");
  ids.pipe_table_delimiter_row = symbol(lang, "pipe_table_delimiter_row");
  ids.thematic_break = symbol(lang, "thematic_break");
  ids.block_quote = symbol(lang, "block_quote");
  ids.block_quote_marker = symbol(lang, "block_quote_marker");
  ids.list = symbol(lang, "list");
  ids.list_item = symbol(lang, "list_item");
  ids.marker_dot = symbol(lang, "list_marker_dot");
  ids.marker_paren = symbol(lang, "list_marker_parenthesis");
  ids.task_checked = symbol(lang, "task_list_marker_checked");
  ids.task_unchecked = symbol(lang, "task_list_marker_unchecked");
  ids.fenced_code_block = symbol(lang, "fenced_code_block");
  ids.code_fence_content = symbol(lang, "code_fence_content");
  ids.fence_delimiter = symbol(lang, "fenced_code_block_delimiter");
  ids.info_string = symbol(lang, "info_string");
  ids.indented_code_block = symbol(lang, "indented_code_block");
  ids.html_block = symbol(lang, "html_block");
  ids.minus_metadata = symbol(lang, "minus_metadata");
  ids.plus_metadata = symbol(lang, "plus_metadata");
  ids.atx_markers[0] = symbol(lang, "atx_h1_marker");
  ids.atx_markers[1] = symbol(lang, "atx_h2_marker");
  ids.atx_markers[2] = symbol(lang, "atx_h3_marker");
  ids.atx_markers[3] = symbol(lang, "atx_h4_marker");
  ids.atx_markers[4] = symbol(lang, "atx_h5_marker");
  ids.atx_markers[5] = symbol(lang, "atx_h6_marker");
  ids.list_markers[0] = symbol(lang, "list_marker_plus");
  ids.list_markers[1] = symbol(lang, "list_marker_minus");
  ids.list_markers[2] = symbol(lang, "list_marker_star");
  ids.list_markers[3] = symbol(lang, "list_marker_dot");
  ids.list_markers[4] = symbol(lang, "list_marker_parenthesis");
  return ids;
}
